export const FINES_ACTIONS = {
    PAY: 'PAY',
    REQUEST: 'ASK',
    VIEW_HISTORY: 'VIEW_HISTORY',
    EXPORT_PHOTO: 'EXPORT_PHOTO',
    EXPORT: 'EXPORT',
    REPORT: 'REPORT',
    PRINT: 'PRINT'
};

export const AVAILABLE_ACTIONS_FOR_SINGLE_SELECTION = [
    FINES_ACTIONS.VIEW_HISTORY
];
